import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        saffron:          '#F4A023',
        turmeric:         '#E8831A',
        forest:           '#2D6A4F',
        sage:             '#74B49B',
        cream:            '#FDF6EC',
        'warm-white':     '#FFFAF3',
        vata:             '#7EC8E3',
        'vata-dark':      '#4A90D9',
        pitta:            '#FF6B6B',
        'pitta-dark':     '#E8831A',
        kapha:            '#52796F',
        'kapha-dark':     '#2D6A4F',
        'text-primary':   '#2C1810',
        'text-secondary': '#6B4C3B',
        border:           '#E8D5C0',
        // Design system tokens from Stitch artifacts
        background:                 '#fff8f6',
        surface:                    '#fff8f6',
        'surface-bright':           '#fff8f6',
        'surface-dim':              '#f8d2c4',
        'surface-container':        '#ffe9e2',
        'surface-container-low':    '#fff1ec',
        'surface-container-high':   '#ffe2d8',
        'surface-container-highest':'#ffdbce',
        'surface-container-lowest': '#ffffff',
        'surface-variant':          '#ffdbce',
        'surface-tint':             '#865300',
        'on-surface':               '#2a170f',
        'on-surface-variant':       '#534434',
        'on-background':            '#2a170f',
        primary:                    '#865300',
        'primary-container':        '#f4a023',
        'primary-fixed':            '#ffddb8',
        'primary-fixed-dim':        '#ffb960',
        'on-primary':               '#ffffff',
        'on-primary-container':     '#623c00',
        'on-primary-fixed':         '#2b1700',
        'on-primary-fixed-variant': '#653e00',
        'inverse-primary':          '#ffb960',
        secondary:                  '#2c694e',
        'secondary-container':      '#aeeecb',
        'secondary-fixed':          '#b1f0ce',
        'secondary-fixed-dim':      '#95d4b3',
        'on-secondary':             '#ffffff',
        'on-secondary-container':   '#316e52',
        'on-secondary-fixed':       '#002114',
        'on-secondary-fixed-variant':'#0e5138',
        tertiary:                   '#904d00',
        'tertiary-container':       '#ff993a',
        'tertiary-fixed':           '#ffdcc3',
        'tertiary-fixed-dim':       '#ffb77d',
        'on-tertiary':              '#ffffff',
        'on-tertiary-container':    '#6a3700',
        'on-tertiary-fixed':        '#2f1500',
        'on-tertiary-fixed-variant':'#6e3900',
        error:                      '#ba1a1a',
        'error-container':          '#ffdad6',
        'on-error':                 '#ffffff',
        'on-error-container':       '#93000a',
        outline:                    '#857462',
        'outline-variant':          '#d8c3ae',
        'inverse-surface':          '#422b22',
        'inverse-on-surface':       '#ffede7',
      },
      fontFamily: {
        display:          ['Playfair Display', 'serif'],
        body:             ['Inter', 'sans-serif'],
        mono:             ['JetBrains Mono', 'monospace'],
        sanskrit:         ['Noto Serif Devanagari', 'serif'],
        'display-lg':     ['Playfair Display', 'serif'],
        'headline-lg':    ['Playfair Display', 'serif'],
        'headline-md':    ['Playfair Display', 'serif'],
        'label-md':       ['Inter', 'sans-serif'],
        'body-lg':        ['Inter', 'sans-serif'],
        'body-md':        ['Inter', 'sans-serif'],
        'sanskrit-quote': ['Noto Serif Devanagari', 'serif'],
      },
      fontSize: {
        'display-lg':          ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg':         ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg-mobile':  ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-md':         ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md':            ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-lg':             ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':             ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'sanskrit-quote':      ['20px', { lineHeight: '32px', fontWeight: '400' }],
      },
      borderRadius: {
        card:   '16px',
        button: '24px',
        tag:    '8px',
      },
      spacing: {
        'max-width-content': '1200px',
        'margin-mobile':     '20px',
        'margin-desktop':    'auto',
        xs:     '4px',
        sm:     '12px',
        md:     '24px',
        lg:     '40px',
        xl:     '64px',
        gutter: '16px',
      },
    },
  },
  plugins: [],
}

export default config
